# Generated by Django 5.0.7 on 2024-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitaionFamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_father_name', models.CharField(blank=True, max_length=16)),
                ('husband_mother_name', models.CharField(blank=True, max_length=16)),
                ('husband_father_isdead', models.BooleanField(default=False)),
                ('husband_mother_isdead', models.BooleanField(default=False)),
                ('wife_father_name', models.CharField(blank=True, max_length=16)),
                ('wife_mother_name', models.CharField(blank=True, max_length=16)),
                ('wife_father_isdead', models.BooleanField(default=False)),
                ('wife_mother_isdead', models.BooleanField(default=False)),
                ('chrysanthemum_display', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_bank', models.CharField(blank=True, max_length=8)),
                ('husband_account', models.CharField(blank=True, max_length=32)),
                ('husband_depositor', models.CharField(blank=True, max_length=32)),
                ('husband_father_bank', models.CharField(blank=True, max_length=8)),
                ('husband_father_account', models.CharField(blank=True, max_length=32)),
                ('husband_father_depositor', models.CharField(blank=True, max_length=32)),
                ('husband_mother_bank', models.CharField(blank=True, max_length=8)),
                ('husband_mother_account', models.CharField(blank=True, max_length=32)),
                ('husband_mother_depositor', models.CharField(blank=True, max_length=32)),
                ('wife_bank', models.CharField(blank=True, max_length=8)),
                ('wife_account', models.CharField(blank=True, max_length=32)),
                ('wife_depositor', models.CharField(blank=True, max_length=32)),
                ('wife_father_bank', models.CharField(blank=True, max_length=8)),
                ('wife_father_account', models.CharField(blank=True, max_length=32)),
                ('wife_father_depositor', models.CharField(blank=True, max_length=32)),
                ('wife_mother_bank', models.CharField(blank=True, max_length=8)),
                ('wife_mother_account', models.CharField(blank=True, max_length=32)),
                ('wife_mother_depositor', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_tel', models.CharField(blank=True, max_length=16)),
                ('husband_father_tel', models.CharField(blank=True, max_length=16)),
                ('husband_mother_tel', models.CharField(blank=True, max_length=16)),
                ('wife_tel', models.CharField(blank=True, max_length=16)),
                ('wife_father_tel', models.CharField(blank=True, max_length=16)),
                ('wife_mother_tel', models.CharField(blank=True, max_length=16)),
                ('notice', models.TextField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationGreetingsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('greetings', models.TextField(blank=True, max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name_en', models.CharField(blank=True, max_length=16)),
                ('husband_firstname', models.CharField(blank=True, max_length=16)),
                ('husband_lastname', models.CharField(blank=True, max_length=4)),
                ('husband_pos', models.CharField(blank=True, max_length=4)),
                ('wife_name_en', models.CharField(blank=True, max_length=16)),
                ('wife_firstname', models.CharField(blank=True, max_length=16)),
                ('wife_lastname', models.CharField(blank=True, max_length=4)),
                ('wife_pos', models.CharField(blank=True, max_length=4)),
                ('title_image', models.ImageField(blank=True, upload_to='res/image/')),
                ('wedding_datetime', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationLocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, max_length=256)),
                ('weddinghall_name', models.CharField(blank=True, max_length=32)),
                ('floor_or_hall', models.CharField(blank=True, max_length=32)),
                ('weddinghall_tel', models.CharField(blank=True, max_length=16)),
                ('transportation', models.TextField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
