# Generated by Django 5.0.7 on 2024-08-19 09:29

import django.db.models.deletion
import invitationapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaionfamilyinfo',
            name='chrysanthemum_display',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invitaionfamilyinfo',
            name='husband_father_isdead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invitaionfamilyinfo',
            name='husband_mother_isdead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invitaionfamilyinfo',
            name='wife_father_isdead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invitaionfamilyinfo',
            name='wife_mother_isdead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invitationinfo',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=invitationapp.models.GetTitleImagePath),
        ),
        migrations.CreateModel(
            name='InvitationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=invitationapp.models.GetGalleryImagePath)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
