# Generated by Django 5.0.7 on 2024-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationapp', '0002_alter_invitaionfamilyinfo_chrysanthemum_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationlocationinfo',
            name='address',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
